[package]
name = "programming_rust"
version = "0.1.0"
authors = ["Billy Kore <billyimmcul2010@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0", features = ["derive"] }
num = "0.4"
image = "0.25.2"
crossbeam = "0.8"
text-colorizer = "1"
regex = "1"
